### ISSUE TITLE
First or last 8 bytes?

### ISSUE THREAD

**Issue by antifob** [csgames/cscoins#1]
In the description, it is the first.
In the example, it is the last.

**Comment by mbinette91** [comment]
I love u uqam

**Comment by antifob** [comment]
I love how you mix the 8 first bytes of a byte string with the last 8 bytes of an integer on l-e machines.

**Comment by leameow** [comment]
Sorry, typo!
Fixed by f220868, use the first 8 bytes.

**Comment by antifob** [comment]
Do we get a coin for my find? :P

**Comment by leameow** [comment]
![image](https://cloud.githubusercontent.com/assets/1420974/23172466/d1790704-f823-11e6-85ee-c1351a4b1bdf.png)

**Comment by antifob** [comment]
Printed! I'll bring it to the exchange on March 24th.
Anyway, thanks.

**Comment by marctrem** [comment]
MERCI FOB T LE MEILLEURRRRRR <3
