### ISSUE TITLE
Grid - Blockers on borders

### ISSUE THREAD

**Issue by antifob** [csgames/cscoins#10]
Hi,

The specification document does not specify whether we should drop blockers that appear on
borders. Should they be dropped or placed on top?

Thanks

**Comment by jordsti** [comment]
I forgot to mention this, I'll update the readme this evening. But if the blocker already exists, you can ignore it. I'll update the code too.

**Comment by antifob** [comment]
Ok thanks.

Please watch out for the phrasing:
Ignore it as in generate another one or as put it on top (as in, there would be no added blocker)?

**Comment by jordsti** [comment]
Ignore and don't generate another one, it counts toward the nb_blockers
