### ISSUE TITLE
Message Types

### ISSUE THREAD

**Issue by arteymix** [csgames/cscoins#12]
Is it possible to add a `type` entry in the responses to dispatch properly the received messages? 

The WebSocket protocol does not really ensure a serial request-response flow, so I have to inspect payloads for the existence of some properties, which is somewhat hackish.

**Comment by jordsti** [comment]
A type field has been added into the response.

**Comment by arteymix** [comment]
Maybe merge all errors under a single `error` type? With a `for` property to include the corresponding command, it would be neat.

```json
{ 
    "type": "error", 
    "for": {"command": "submission", "args": {}},
    "error": "some descriptive message",
    ...
}
```

Others types looks good to me.

**Comment by jordsti** [comment]
I'll keep the type as it is at the moment,
