### ISSUE TITLE
Submission - No error message

### ISSUE THREAD

**Issue by antifob** [csgames/cscoins#13]
Hi,

As specified the server is supposed to send an error message when an invalid submission is sent.
At the moment, it does not.

Thanks

**Comment by jordsti** [comment]
There's actually no error message for an invalid submission. I can push an error message if it's invalid after the verification, but you won't receive it right after the submission command. You should avoid sending invalid submission, because you can be temporary ban if you send too many invalid submission.

**Comment by antifob** [comment]
Actually, I wanted you to notice that, upon startup, the server will accept any and all submissions.

That means that the first submission of the event will (in the current state) be accepted and that, if the server crashes and it restarted, the first submission upon restart will be accepted too.

If a team is able to make the server crash and be the first to submit, that's free points all w-e.

**Comment by jordsti** [comment]
It's fixed.

**Comment by antifob** [comment]
(nvm, error on my part)

**Comment by antifob** [comment]
On further inspection, on restart ChallengeThread checks submissions against '0'x64 instead of recovering the last_solution_hash from the database. This causes the PRNG to be seeded incorrectly as the last_solution_hash sent to client is properly recovered from the database.

At the moment, I'm unclear whether this causes the first submission to always be rejected.

I can create another issue if you prefer?

(edit: phrasing)

**Comment by antifob** [comment]
Update, now the first submission is always rejected (unless the client willfully used 0x64 as the last_solution_hash, despite not being the one received).

**Comment by jordsti** [comment]
Try with the last commit. I pushed a fix 3 minutes ago.

**Comment by antifob** [comment]
fixed thanks
