### ISSUE TITLE
MySQL nonce field not big enough

### ISSUE THREAD

**Issue by Quinny** [csgames/cscoins#15]
BIGINT in MySQL is a **signed** 64 bit integer.  Therefore attempting to submit a 64 bit unsigned integer such as `13465558713502331910` results in an error, when it shouldn't.

I think you should be using the `SERIAL` type instead.
https://dev.mysql.com/doc/refman/5.7/en/numeric-type-overview.html

**Comment by jordsti** [comment]
Ohh I forgot the unsigned keyword. I'll fix this tonight.

Serial isn't the wanted type, because it also contains AUTO_INCREMENT and UNIQUE, it's only an alias.

**Comment by Quinny** [comment]
Sounds good.

I also noticed that sometimes the database does not throw an exception and the submission.nonce silently overflows to the largest signed 64 bit integer.  This creates an inconsistency with the submission and what appears in the database.

**Comment by Quinny** [comment]
Fixed in https://github.com/csgames/cscoins/commit/d06fc8dce2bd685b8069d92ded5ba85441223201
