### ISSUE TITLE
Shortest Path Neighbour Ordering

### ISSUE THREAD

**Issue by Quinny** [csgames/cscoins#16]
You state in the documentation that you check the neighbour's for the shortest path in the following order: `down, up, right, left.`

But then in the solver on line 38:
https://github.com/csgames/cscoins/blob/master/src/caserver/challenges/ShortestPathChallenge.py#L38

You reverse the order if (row + col) % 2 == 0.  This will create inconsistencies with the paths generated.  Is there a reason for this?  I these two lines could be removed and the solver would be consistent with the documentation.

**Comment by jordsti** [comment]
You're right. I removed the tuple reverse.
