### ISSUE TITLE
Pay-to-win

### ISSUE THREAD

**Issue by becojo** [csgames/cscoins#2]
Je me demandais, si une team peux se payer une fuck ton de d'instance EC2 sur AWS ou a accès à un super ordinateur pour miner des CS Coins, c'est pas un peu un genre "pay-to-win" comme compétition? 

(j'ai entendu entre les branches que vous alliez fournir des environnements identiques aux teams)

**Comment by antifob** [comment]
+1 so we can say: "we won because of technical merit". /s

**Comment by jordsti** [comment]
On a pensé à ce problème et le but n'est pas de faire un pay-to-win. On veut que les teams soient toutes égales.

**Comment by leameow** [comment]
La seule limitation risque d'être le CA sur le réseau interne. On a pas vraiment trouvé d'idée révolutionnaire pour limiter ce use-case sans:
 1. Avoir à supporter une infra fermé ou le monde submit leur mineur et croise les doigts que leur truc à le runtime et dépendances nécessaire. Also, debugging hell.
 2. N'est pas contournable avec une simple tunnel vers les intertubes.

**Comment by marctrem** [comment]
Zut, je voulais justement tuneler :(

**Comment by leameow** [comment]
*Quick head up*: we might have a solution where miners will be running on an isolated environment and won't be able to submit a solution if they have been reaching out the network. So in short, don't assume you will be able to distribute your miners and pay to win.
