### ISSUE TITLE
RSA key size

### ISSUE THREAD

**Issue by Cyberunner23** [csgames/cscoins#22]
Out of curiosity would it be possible for a client to use a larger RSA keypair? (such as a 2048bit key)

**Comment by antifob** [comment]
Have you found a weakness in RSA that leads you to think 1024 will be broken this w-e?

**Comment by Cyberunner23** [comment]
No its not about a weakness, its about the library we are using not
supporting 1024 bit keys, guess the devs think they are too weak for
anything. Anyhow we figured it out.
