### ISSUE TITLE
Clarify signatures

### ISSUE THREAD

**Issue by arteymix** [csgames/cscoins#23]
In the `register_wallet` command, the raw SHA256 hash of the DER-encoded public key is signed, but in general the signature scheme expect a concatenation of values with a `,` separator. 

Thus, I would have expected to simply pass the hexified version of `wallet_id` to the signature process (e.g. apply `sha256` on the hexified `wallet_id`).

Also, the signature protocol does not specify that SHA256 is used.

**Comment by jordsti** [comment]
I clarified the hashing algorithm for the Signature. But for the registration, we will keep the raw hash of the DER-encoded public key. Because you already need this hash to know your `wallet_id`. Instead of doing another hash after.

**Comment by antifob** [comment]
haha, nvm. I thought you were talking about the registration, not submission.

**Comment by arteymix** [comment]
It's still not clarifying that the raw wallet id sha256 is used as a signature for `register_wallet`. I was confused when implementing the client side crypto because I though that the content to be signed was the hexified `wallet_id`.

Here you say:

> The Wallet Id is a SHA256 Hash of a client public key in DER (Distinguished Encoding Rules) format.

In general, this mean it is a hexdigest string.

Though here it means the raw sha256 bytes used for the signature:

> Message signature in hexadecimal format. The signed message used is the wallet_id being registered.

**Comment by jordsti** [comment]
Ok, I just change it to:

> Message signature in hexadecimal format. The message used for the signature is the public key in DER format.

**Comment by arteymix** [comment]
That's excellent :+1:
