### ISSUE TITLE
Difficulty of challenges

### ISSUE THREAD

**Issue by JesseEmond** [csgames/cscoins#26]
Will a difficulty be chosen during the weekend such that a block takes an approximate fixed amount of time to be mined (e.g. pick a hash prefix length such that blocks are mined every `~10` minutes)? If you guys will aim for a particular block mining time, would it be possible to know what that timing would be?

Context: our miner does not continually check if the thread is still alive like the reference miner and knowing the order of magnitude of the expected mining time (seconds vs minutes) would help to balance when to check for an early stopping condition.

**Comment by jordsti** [comment]
We will target a 5 to 10 minutes. But you will receive a message with the new challenge when a new one is available.
