### ISSUE TITLE
Taille du nonce

### ISSUE THREAD

**Issue by becojo** [csgames/cscoins#4]
Est-ce que la taille du nonce va être connu? 

Ça semble être configurable dans le serveur donc j'imagine que les valeurs ne seront pas les mêmes aux CS.

**Comment by leameow** [comment]
La taille du nonce est pas définis nulle part dans la spec, c'est toi qui le génère. Ou tu parle du préfix?

**Comment by becojo** [comment]
Ces valeurs la https://github.com/csgames/cscoins/blob/master/src/caserver/challenges/BaseChallengeGenerator.py#L14-L15

**Comment by leameow** [comment]
@jordsti (Auteur) peut probablement confirmer, mais c'est pas vraiment utiliser ce code là.

**Comment by jordsti** [comment]
C'est pour générer une solution random, pour seulement récupérer le prefix pour créer un challenge, mais le range a pas d'importance, car tu vas trouver une solution avec un autre nonce.

**Comment by becojo** [comment]
Donc c'est legit que le miner hardcode ces valeurs?

https://github.com/csgames/cscoins/blob/master/src/minerclient/ChallengeSolver.py#L29

**Comment by jordsti** [comment]
Pour l'instant le miner hardcode les même limites, mais dans les prochaines modifications, je vais juste générer un uint32 random. Mais dans ton miner tu peux utiliser une limite ou non, car tu vas trouver une solution qui n'aura pas le même nonce que le serveur. Seulement la solution doit être valide.

**Comment by becojo** [comment]
Right.

Généralement ça donne pas mal la même valeur de ce que je vois.

C'est bon merci.
