### ISSUE TITLE
Comment savoir si le challenge à été solve

### ISSUE THREAD

**Issue by Balnian** [csgames/cscoins#5]
A part poker le serveur en continu y aurait-il manière de savoir si le challenge à été solve? Genre recevoir un push sur le websocket avec le nouveau challenge?

**Comment by jordsti** [comment]
Je vais ajouter un push du nouveau challenge, d'ici vendredi.

**Comment by Balnian** [comment]
Cool merci

**Comment by jordsti** [comment]
Après avoir fait un get_current_challenge, les autres vont être push automatiquement.

https://github.com/csgames/cscoins/blob/master/README.md#get-current-challenge
