### ISSUE TITLE
Environment

### ISSUE THREAD

**Issue by antifob** [csgames/cscoins#6]
Hi,

Couple of questions:
- What is the OS?
- Are miners-CA communications encrypted (i.e. TLS)? If so, will the miners already have the certificate?
- Will the teams be able to install missing tools or libraries?
- Will the teams be able to monitor (SSH or other) and adapt their miners during the event?

Thanks

**Comment by jordsti** [comment]
> What is the OS?

It will be Linux, we haven't officially choose the distribution yet. We will communicate the choice.

> Are miners-CA communications encrypted (i.e. TLS)? If so, will the miners already have the certificate?

Yes, we will use a valid SSL certificate with the Secure Web Socket, we don't want you to sniff the other miner solution.

> Will the teams be able to install missing tools or libraries?

Yes

> Will the teams be able to monitor (SSH or other) and adapt their miners during the event?

Yes of course, but we will enforce some rules.
> we might have a solution where miners will be running on an isolated environment and won't be able to submit a solution if they have been reaching out the network. So in short, don't assume you will be able to distribute your miners and pay to win.

https://github.com/csgames/cscoins/issues/2

**Comment by cannotparse** [comment]
Inline with the first question. 

- What hardware should we expect the miners to run on?
   - 12 cores VM or 12 cores bare metal? 
   - Intel Xeons? Which generation?
   - CUDA or OpenCL hardware available? 
- Are the miners supposed to be ready Friday night and supposed to keep running until Sunday? Or will you bench them individually?
   - Is this an arms race to get the most coins or the best miner at the end wins?

As much as I'd love to provide code for all hardware available, I've got courses to pass :P

**Comment by marctrem** [comment]
KVMGT pls

**Comment by jordsti** [comment]
> What hardware should we expect the miners to run on? 

It will be a "X" cores VM, not sure on the number of cores at the moment. Don't focus on hardware specific instructions. It will probably be a x86-64 architecture.

> CUDA or OpenCL hardware available?

No GPGPU compute available.

> Are the miners supposed to be ready Friday night and supposed to keep running until Sunday? 

They will start on Friday 7pm (beginning of competitions), it will end on Sunday 12h pm.

> Is this an arms race to get the most coins or the best miner at the end wins?

Team that mines the highest numbers of coins during the event.

**Comment by Balnian** [comment]
Can we know what VM Tech you will use? (ESXI, Xen, ...) For those who want to test their miner on the same stack

**Comment by antifob** [comment]
Any update on the stack?

**Comment by jvalinsky** [comment]
Would it be possible to allow access for programs that aren't miners that just query the transaction list? Maybe specifically disallow mining from clients that are able to communicate outside the network? I feel like that could allow for neat things like a web app showing leader board/live stats for each wallet address. 
Since the theme is "Silicon Valley"/start up culture, this would allow for innovation and be in the spirit of the competition.

**Comment by MichaelNecio** [comment]
Newest versions of GCC and Clang that will be available?

**Comment by jordsti** [comment]
> Any update on the stack?

We will probably (we got some last minutes test to do before) use docker, you will be able to run one container for your miner.

>Would it be possible to allow access for programs that aren't miners that just query the transaction list? 

Everybody will be able to query the transactions list. The only thing restricted to a network, will be the submission of a challenge.

**Comment by antifob** [comment]
> We will probably (we got some last minutes test to do before) use docker, you will be able to run one container for your miner.

We will all be running inside a container or run the miners in containers?

Thanks for the update.

**Comment by marctrem** [comment]
The latter
