### ISSUE TITLE
Abusive clients

### ISSUE THREAD

**Issue by arteymix** [csgames/cscoins#7]
What will be done to prevent or determine abusive clients?

**Comment by leameow** [comment]
What do you mean?

**Comment by arteymix** [comment]
The simplest case would be to flood the network and prevent others from receiving challenges while computation is in-progress.

There's a lot of other possible *attacks* like dropping other's TCP connections or requesting the server to perform costful tasks for nothing (e.g. verifying a wrong submission).

**Comment by jordsti** [comment]
Theses kind of things will be considered as cheating and will be penalised. For the wrong submission case, we will add a cool down on wrong submission that will increase if you continue to submit invalid solution.

**Comment by arteymix** [comment]
Good, I really want to play fair here, but game theory unfortunately prevales.
