### ISSUE TITLE
Which Shortest Path?

### ISSUE THREAD

**Issue by joeljk13** [csgames/cscoins#9]
The current specification for the shortest path challenge (in the README) doesn't specify which shortest path to use if multiple exist. In the example shown, going 4 down and then 2 right also gives the same length. The example also doesn't show a preference for which direction to go if multiple work.

The server code given checks a nonce by generating its solution, and checking the hash of that, which will probably be different than the hash of a different solution.

Could we get an official specification of which path to use? If how the current server code generates a solution is the specification, that works; I'm just worried that my code might become wrong if the server solution code gets updated.

**Comment by jordsti** [comment]
I reviewed the README, I added some clarification on the solution path.

You can also look at the server source code to know how we solve the challenge. We won't changes that code except if we found a major bug. But this repository will stay the updated during the event, if a change occurs, you will be able to consult the code change.

**Comment by joeljk13** [comment]
What if there is no path at all from the start point to the end point? Currently it looks like the server code crashes when trying to reconstruct the path.

**Comment by jordsti** [comment]
It's not a valid challenge or solution when there's no path. This is actually handled, and it's not generating a crash.

**Comment by joeljk13** [comment]
Whoops, tested the wrong thing, sorry. It looks like the README has the direction orders wrong (it should be up, left, right, down, I think), but example's correct and I can just follow the code from here. Thanks!
